// <auto-generated />
using System;
using Kusys.Data.Concreate.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kusys.Data.Migrations
{
    [DbContext(typeof(KusysContext))]
    partial class KusysContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Kusys.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"), 1L, 1);

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            CourseId = 101,
                            CourseName = "Introduction to Computer Science"
                        },
                        new
                        {
                            CourseId = 102,
                            CourseName = "Algorithms"
                        },
                        new
                        {
                            CourseId = 103,
                            CourseName = "Calculus"
                        },
                        new
                        {
                            CourseId = 104,
                            CourseName = "Physics"
                        });
                });

            modelBuilder.Entity("Kusys.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Kusys.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("StudentId");

                    b.HasIndex("RoleID");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            BirthDate = new DateTime(2022, 11, 20, 14, 9, 14, 845, DateTimeKind.Local).AddTicks(1508),
                            FirstName = "Semih",
                            LastName = "Özhan",
                            RoleID = 1,
                            password = "password",
                            username = "username"
                        },
                        new
                        {
                            StudentId = 2,
                            BirthDate = new DateTime(2022, 11, 20, 14, 9, 14, 845, DateTimeKind.Local).AddTicks(1518),
                            FirstName = "Semih2",
                            LastName = "Özhan2",
                            RoleID = 1,
                            password = "password",
                            username = "username2"
                        },
                        new
                        {
                            StudentId = 3,
                            BirthDate = new DateTime(2022, 11, 20, 14, 9, 14, 845, DateTimeKind.Local).AddTicks(1519),
                            FirstName = "Semih3",
                            LastName = "Özhan3",
                            RoleID = 1,
                            password = "password",
                            username = "username3"
                        });
                });

            modelBuilder.Entity("Kusys.Entities.StudentCourse", b =>
                {
                    b.Property<int>("StudentCourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentCourseId"), 1L, 1);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("StudentCourseId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentCourse");

                    b.HasData(
                        new
                        {
                            StudentCourseId = 1,
                            CourseId = 101,
                            StudentId = 1
                        },
                        new
                        {
                            StudentCourseId = 2,
                            CourseId = 102,
                            StudentId = 1
                        });
                });

            modelBuilder.Entity("Kusys.Entities.Student", b =>
                {
                    b.HasOne("Kusys.Entities.Role", "Role")
                        .WithMany("Students")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Kusys.Entities.StudentCourse", b =>
                {
                    b.HasOne("Kusys.Entities.Course", "Course")
                        .WithMany("StudentCourse")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kusys.Entities.Student", "Student")
                        .WithMany("StudentCourse")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Kusys.Entities.Course", b =>
                {
                    b.Navigation("StudentCourse");
                });

            modelBuilder.Entity("Kusys.Entities.Role", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Kusys.Entities.Student", b =>
                {
                    b.Navigation("StudentCourse");
                });
#pragma warning restore 612, 618
        }
    }
}
